version: '3'

services:
  tensorflow:
    build: .
    volumes:
      - ./nyc-taxis:/usr/taxis
      - ./Titanic:/usr/titanic
      - ./:/notebooks
      - ./TalkingDataFraud:/usr/fraud
    ports:
      - 5001:8888