FROM ubuntu:16.04

MAINTAINER RicardoTrindade <ricardo.trindade743@gmail.com>

# Pick up some TF dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python \
        python-dev \
        rsync \
        wget \
        software-properties-common \
        unzip \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip --no-cache-dir install \
        Pillow \
        h5py \
        ipykernel \
        jupyter \
        matplotlib \
        numpy \
        pandas \
        scipy \
        sklearn \
        seaborn \
        keras \
        && \
    python -m ipykernel.kernelspec

# RUN ln -s /usr/bin/python3 /usr/bin/python#

# TensorBoard
EXPOSE 6006
# IPython
EXPOSE 8888